os: linux
version: 0.0
files:
  - source: Config/config.txt
    destination: /opt/apache-tomcat-8.0.23/webapps/Config
  - source: index.jsp
    destination: /opt/apache-tomcat-8.0.23/webapps/myApp
hooks:
  BeforeInstall:
    - location: Scripts/CleanUp.sh
  ApplicationStart:
    - location: Scripts/StartApp.sh
      timeout: 3600
  ValidateService:
    - location: Scripts/MonitorApp.sh
      timeout: 3600
