os: linux
version: 0.0
files:
  - source: Config/config.txt
    destination: /webapps/Config
  - source: index.jsp
    destination: /webapps/myApp
hooks:
  BeforeInstall:
    - location: Scripts/CleanUp.sh
  ApplicationStart:
    - location: Scripts/StartApp.sh
      timeout: 3600
  ValidateService:
    - location: Scripts/MonitorApp.sh
      timeout: 3600
